---
- name: Firewall - Allow SSH connections
  ufw:
    rule: allow
    name: OpenSSH
  tags:
    - firewall

- name: Firewall - Deny everything else
  ufw:
    state: enabled
    policy: deny
  tags:
    - firewall

